apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backstage-pg
  name: backstage-pg
  namespace: tekton-temp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-pg
  template:
    metadata:
      labels:
        app: backstage-pg
    spec:
      containers:
      - image: bitnami/postgresql:13
        name: postgresql
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USERNAME
          value: backstage
        - name: POSTGRESQL_PASSWORD
          value: backstagePass123
