apiVersion: v1
kind: Service
metadata:
  labels:
    app: hero-pg
  name: hero-pg
  namespace: tekton-temp
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: hero-pg
  type: ClusterIP
