apiVersion: v1
kind: ServiceAccount
metadata:
  name: ansible-deployer-account
  namespace: dummy
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ansible-deployer
  namespace: tekton-temp
rules:
  # Core API
  - apiGroups: ['']
    resources: ['services', 'pods', 'deployments', 'configmaps', 'secrets']
    verbs: ['get', 'list', 'create', 'update', 'delete', 'patch', 'watch']
  # Apps API
  - apiGroups: ['apps']
    resources: ['deployments', 'daemonsets', 'jobs']
    verbs: ['get', 'list', 'create', 'update', 'delete', 'patch', 'watch']
  # Knative API
  - apiGroups: ['serving.knative.dev']
    resources: ['services', 'revisions', 'routes']
    verbs: ['get', 'list', 'create', 'update', 'delete', 'patch', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ansible-deployer-binding
  namespace: tekton-temp
subjects:
  - kind: ServiceAccount
    name: ansible-deployer-account
    namespace: dummy
roleRef:
  kind: Role
  name: ansible-deployer
  apiGroup: rbac.authorization.k8s.io
