- hosts: localhost
  connection: local
  collections:
    - kubernetes.core
  tasks:
    - name: Create a new Service
      k8s:
        state: {{ state }}
        src: {{ src }}
        wait: yes
      register: svc

    - name: Get the Service
      k8s_info:
        kind: Service
        namespace: tekton-temp
      register: tekton_temp_svc_list

    - name: Log Service Details
      debug:
        msg: "{{ item | json_query('metadata.name') }}"
      loop: '{{tekton_temp_svc_list.resources}}'
      loop_control:
        label: "Service (Namespace: {{item | json_query('metadata.namespace')}})"

